### ISSUE TITLE
bin/uri is missing a dependency

### ISSUE THREAD

**Issue by g-gundam** [pip/Octology#2]
When I run `uri`, it crashes with this message:

```
Can't locate URI.pm in @INC (you may need to install the URI module) (@INC contains: /home/pip/lib /home/pip/lib/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/pip/lib/perl5/lib/perl5 ./lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/pip/bin/uri line 4.
BEGIN failed--compilation aborted at /home/pip/bin/uri line 4.
```

**Comment by pip** [comment]
Hello g-gundam. Thank you for opening this issue. I've upd8d the Dockerfile to both install liburi-perl for Ubuntu as well as `cpanm URI` down where the container installs CPAN modules. I'll include these changes with the next commit I make to my local repository and should push them up to GitHub shortly after. This should occur possibly later tonight, but might not be done until further along in the week. Since the module is not authored or managed by me, probably the best thing you can do to resolve it yourself would be:

  0. Run `cpanm URI`  # if you have cpanminus already
  1. Run `cpan  URI`  # ... or without the m if you just have it
  2. Run `perl -MCPAN -e "install URI"`  # ... or this should do almost the same as both of the above

Hopefully any one of these should resolve your issue in one of the most reasonable and preferable ways to do so. It's not my module, so please simply get the latest version from the CPAN and install it yourself. If you have trouble doing so, feel free to reply in this thread and I will be glad to try to help you further, if you might need more guidance about getting your own local CPAN.pm (and configur8ion for it) setup to function correctly.

Thanks again. Hope that helps. Have a nice day.  -Pip  =)

**Comment by pip** [comment]
Hello again g-gundam. I still have not yet pushed up the improved Dockerfile and other repo changes I've made, but expect to become able to do so rel8ively soon. Since I provided you those instructions above, and you have not replied in 4 Days to indic8 that this issue remains as something I should attend further to, I've decided to close it with this comment. Hopefully you're satisfied that installing URI from the CPAN yourself provides sufficient resolution. Thanks again for filing the issue though. I'm glad you're trying out Octology and I stay eager to help you and others use it effectively. Please don't hesit8 to e-mail or message me if there's any other way I might help you learn to enjoy using this project. Peace!  -Pip  =)
